apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: logs
    isDefault: true
    jsonData:
      timeField: timestamp
      esVersion: 7.10.0
